version: "3.8"

x-app-common:
  &app-common
  image: ${APP_NAME}:latest
  build: .
  env_file:
    - .env.${APP_ENV}
  networks:
    - redis
    - db
    - cache

services:
  app:
    <<: *app-common
    command: >
      gunicorn ${APP_NAME}.wsgi:application
        --name app-gunicorn
        --bind 0.0.0.0:8000
        --workers 4
        --worker-tmp-dir /dev/shm
        --pythonpath "/opt/app"
        --log-level=info
        --timeout 120
    ports:
      - ${APP_PORT}:8000

  celery-worker:
    <<: *app-common
    command: python -m celery -A digicloud worker --loglevel=INFO

  celery-beat:
    <<: *app-common
    command: python -m celery -A digicloud beat --loglevel=INFO

  redis:
    image: redis:6
    command: ["redis-server", "--appendonly", "no", "--save", "", "--maxmemory", "1gb", "--maxmemory-policy", "allkeys-lru"]
    networks:
      - redis

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.${APP_ENV}
    networks:
      - db

  memcached:
    image: memcached:1-alpine
    networks:
      - cache

volumes:
  postgres_data:

networks:
  db:
  cache:
  redis:
